#!/bin/bash

while ! ping -W 1 -c 1 10.44.12.1; do
    sleep 1
done

echo "log target: Bootup complete" | nc 10.44.12.1 2500

(
    echo "log target: PCR values are:"
    cat $(find /sys/devices -name pcrs | head -n1)
) | nc 10.44.12.1 2500

echo "exit 0" | nc 10.44.12.1 2500

