#!/bin/bash

cd /root

while ! ping -W 1 -c 1 10.44.12.1; do
    sleep 1
done

echo "log baremetal-report: Downloading input.tar" | nc 10.44.12.1 2500

wget -U baremetal -O input.tar http://10.44.12.1/baremetal/input.tar
if [ -e input.tar ]; then
    echo "log baremetal-report: Unpacking input.tar" | nc 10.44.12.1 2500
    tar xf input.tar
    chmod a+x main
    mkdir output
    ./main
    rc="$?"
    echo "log baremetal-report: ./main exited with code $rc" | nc 10.44.12.1 2500
    echo "log baremetal-report: Uploading output.tar" | nc 10.44.12.1 2500
    (echo -n "output "; tar -C output -cf - . | gzip -9 | base64 | tr -d '\n') | nc 10.44.12.1 2500
else
    echo "log baremetal-report: No input.tar was found" | nc 10.44.12.1 2500
fi

echo "exit 0" | nc 10.44.12.1 2500

