#!/bin/bash

upload_output() {
    echo "log baremetal-report: Uploading output.tar" | nc 10.44.12.1 2500
    (echo -n "output "; tar -C output -cf - . | gzip -9 | base64 | tr -d '\n') | nc 10.44.12.1 2500
}

case "$1" in
    "exit")
	echo "log baremetal-report: ./main called baremetal_exit with code $2" | nc 10.44.12.1 2500
	upload_output
	echo "exit 0" | nc 10.44.12.1 2500
	;;
    "output")
	upload_output
	;;
esac

     
