#!/bin/bash

if [ ! -e /usr/local/bin/baremetal-agent ]; then
    while ! ping -W 1 -c 1 10.44.12.1; do
	sleep 1
    done
    wget -U baremetal -O /usr/local/bin/baremetal-agent http://10.44.12.1/baremetal/baremetal-agent
    chmod a+x /usr/local/bin/baremetal-agent
fi
/usr/local/bin/baremetal-agent
